# General
device = "cuda"
input_dim = 1
output_dim = 1

# Dataset Encoder
dataset_encoder_type = "set_transformer"
dataset_representation_dim = 128
set_transformer_num_heads = 4
set_transformer_num_inds = 16
set_transformer_ln = true
set_transformer_hidden_dim = 256
set_transformer_num_seeds = 16
x_transf_dim = 128
xy_encoder_hidden_dim = 128
xy_encoder_num_hidden = 2

# Knowledge Encoder
knowledge_representation_dim = 128
text_encoder = "set"
roberta_freeze_llm = true
roberta_tune_llm_layer_norms = false
set_embedding_num_hidden = 1
knowledge_encoder_num_hidden = 2
knowledge_dropout = 0.0

# Understanding Encoder
understanding_representation_dim = 128
knowledge_dataset_merge = "sum"
knowledge_dataset_merger_hidden_dim = 128
knowledge_dataset_merger_num_hidden = 1
understanding_encoder_num_hidden = 2

# Data Interaction Encoder
data_interaction_self_attention_hidden_dim = ...
data_interaction_self_attention_num_heads = ...
data_interaction_cross_attention_hidden_dim = ...
data_interaction_cross_attention_num_heads = ...

# Memory Module
use_memory = ...
memory_slots = ...
memory_gamma = ...

# Latent Encoder Module
data_interaction_understanding_merge = ...
data_interaction_understanding_merger_hidden_dim = ...
data_interaction_understanding_merger_num_hidden = ...
latent_encoder_hidden_dim = ...
latent_encoder_num_hidden = ...
data_interaction_dim = ...

# Decoder Module
decoder_activation = ...
decoder_hidden_dim = ...
decoder_num_hidden = ...
